---
apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics-application-controller
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-application-controller
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.applicationController.servicePort }}
    targetPort: {{ .Values.applicationController.containerPort }}
  selector:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-application-controller