
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: argocd
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
data:
{{- if .Values.config.sso.enabled }}
  url: {{ tpl .Values.config.sso.url . }}
  
  {{- if .Values.config.sso.dexConfig }}
  dex.config: |
{{ toYaml .Values.config.sso.dexConfig | indent 4 }}
  {{- end }}

  {{- if .Values.config.sso.oidcConfig }}
  oidc.config: |
{{ toYaml .Values.config.sso.oidcConfig | indent 4 }}
  {{- end }}
{{- end }}

  {{- if .Values.config.github.repositories }}
  repositories: |
    {{- range .Values.config.github.repositories }}
    - url: {{ .url }}
      sshPrivateKeySecret: 
        name: {{ .sshPrivateKeySecretName }}
        key: sshPrivateKey
    {{- end }}
  {{- end }}

  {{- if .Values.config.helm.repositories }}
  helm.repositories: |
    {{- range .Values.config.helm.repositories }}
    - url: {{ .url }}
      name: {{ .name }}
    {{- end }}
  {{- end }}

  {{- if .Values.config.resource.customizations }}
  resource.customizations: |
{{ toYaml .Values.config.resource.customizations | indent 4 }}
  {{- end }}

  {{- if .Values.config.resource.exclusions }}
  resource.exclusions: |
{{ toYaml .Values.config.resource.exclusions | indent 4 }}
  {{- end }}

  {{- if .Values.config.configManagementPlugins }}
  configManagementPlugins: |
{{ toYaml .Values.config.configManagementPlugins | indent 4 }}
  {{- end }}

  {{- if .Values.config.application.instanceLabelKey }}
  application.instanceLabelKey: {{ .Values.config.application.instanceLabelKey }}
  {{- end }}