---
apiVersion: v1
kind: Service
metadata:
  name: argocd-redis
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-redis
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
spec:
  ports:
    - name: tcp-redis
      protocol: TCP
      port: {{ .Values.redis.image.containerPort }}
      targetPort: {{ .Values.redis.image.containerPort }}
  selector:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-redis
