---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-redis
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argo-cd.name" . }}-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argo-cd.name" . }}-redis
        helm.sh/chart: {{ include "argo-cd.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: redis
        app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
          - "--save"
          - ""
          - "--appendonly"
          - "no"
          ports:
          - containerPort: {{ .Values.redis.containerPort }}
{{- with .Values.redis.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.redis.volumeMounts }}
          volumeMounts:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.redis.volumes }}
      volumes:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.redis.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.redis.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.redis.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.redis.podDnsPolicy }}
      dnsPolicy: {{ .Values.redis.podDnsPolicy }}
{{- end }}
{{- if .Values.redis.podDnsConfig }}
      dnsConfig:
{{ toYaml .Values.redis.podDnsConfig | indent 8 }}
{{- end }}
