---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-server
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
