applicationController:
  containerPort: 8082
  servicePort: 8082
  image:
    repository: argoproj/argocd
    tag: v1.0.0
    pullPolicy: Always

dexServer:
  containerPortHttp: 5556
  containerPortGrpc: 5557
  servicePortHttp: 5556
  servicePortGrpc: 5557
  image:
    repository: quay.io/dexidp/dex
    tag: v2.12.0
    pullPolicy: Always
  initImage:
    repository: argoproj/argocd
    tag: v1.0.0
    pullPolicy: Always
